# -*- coding: utf-8 -*-
"""
الهدف: مصدر الحقيقة لقائمة الموارد الخارجية المستوردة إلى الفدرالية — لكل مورد
       اسمه ورابط مصدره وتصنيفه ومكانه المخصص وتخصصه الدقيق.
النطاق: بيانات فقط. لا منطق ولا آثار جانبية — يقرؤه `generate_imported.py`.
المالك: agents/registry
تاريخ الإنشاء: 2026-08-15
تاريخ آخر تعديل: 2026-08-16

بيانات الوكلاء المستوردين لـ AMOS-Federation — المرحلة 1 (السحب).
"""
# كل عنصر: (الاسم, الرابط, التصنيف العربي, المكان المخصص, التخصص الدقيق)
# المكان المخصص يطابق بنية المستودع الفدرالية.

AGENTS = [
    # ===== أطر العمل الأساسية (Core Frameworks) -> federal-executive =====
    ("AutoGPT", "https://github.com/Significant-Gravitas/AutoGPT", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("LangChain", "https://github.com/langchain-ai/langchain", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Dify", "https://github.com/langgenius/dify", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("MetaGPT", "https://github.com/geekan/MetaGPT", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("OpenHands", "https://github.com/All-Hands-AI/OpenHands", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("AutoGen", "https://github.com/microsoft/autogen", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("LlamaIndex", "https://github.com/run-llama/llama_index", "أطر العمل الأساسية", "federal-executive", "data-framework"),
    ("CrewAI", "https://github.com/joaomdmoura/crewAI", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Semantic Kernel", "https://github.com/microsoft/semantic-kernel", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Haystack", "https://github.com/deepset-ai/haystack", "أطر العمل الأساسية", "federal-executive", "data-framework"),
    ("Botpress", "https://github.com/botpress/botpress", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("OpenClaw", "https://github.com/openclaw/openclaw", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Hermes Agent", "https://github.com/nousresearch/hermes-agent", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Llama Agentic System", "https://github.com/meta-llama/llama-agentic-system", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Transformers Agents", "https://huggingface.co/docs/transformers/transformers_agents", "أطر العمل الأساسية", "federal-executive", "model-framework"),
    ("Lagent", "https://github.com/InternLM/lagent", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("AG2", "https://github.com/ag2ai/ag2", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Agent-LLM", "https://github.com/Josh-XT/Agent-LLM", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("e2b", "https://github.com/e2b-dev/e2b", "أطر العمل الأساسية", "federal-executive", "sandbox"),
    ("Dust", "https://github.com/dust-tt/dust", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("LLM Agents", "https://github.com/mpaepper/llm_agents", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Adala", "https://github.com/HumanSignal/Adala", "أطر العمل الأساسية", "federal-executive", "data-labeling"),
    ("Agent4Rec", "https://github.com/LehengTHU/Agent4Rec", "أطر العمل الأساسية", "federal-executive", "recommendation"),
    ("AgentForge", "https://github.com/DataBassGit/AgentForge", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Agents (aiwaves-cn)", "https://github.com/aiwaves-cn/agents", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("AgentVerse", "https://github.com/OpenBMB/AgentVerse", "أطر العمل الأساسية", "federal-executive", "multi-agent"),
    ("AgentPilot", "https://github.com/jbexta/AgentPilot", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("AI Legion", "https://github.com/eumemic/ai-legion", "أطر العمل الأساسية", "federal-executive", "multi-agent"),
    ("Agency Swarm", "https://github.com/VRSEN/agency-swarm", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("AgenticGoKit", "https://github.com/agenticgokit/agenticgokit", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("AgentOS", "https://github.com/agentos-project/agentos", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("AgentScope", "https://github.com/modelscope/agentscope", "أطر العمل الأساسية", "federal-executive", "multi-agent"),
    ("AgentStack", "https://github.com/AgentStack/AgentStack", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("AGiXT", "https://github.com/Josh-XT/AGiXT", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Qwen-Agent", "https://github.com/QwenLM/Qwen-Agent", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("XAgent", "https://github.com/OpenBMB/XAgent", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Google ADK", "https://github.com/google/adk", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Microsoft Agent Framework", "https://github.com/microsoft/agent-framework", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Coze Studio", "https://github.com/coze-dev/coze-studio", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Flowise", "https://github.com/FlowiseAI/Flowise", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("SuperAGI", "https://github.com/TransformerOptimus/SuperAGI", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("OpenAI Agents SDK", "https://github.com/openai/openai-agents-python", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("DSPy", "https://github.com/stanfordnlp/dspy", "أطر العمل الأساسية", "federal-executive", "prompt-optimization"),
    ("Guidance", "https://github.com/guidance-ai/guidance", "أطر العمل الأساسية", "federal-executive", "prompt-framework"),
    ("LMQL", "https://github.com/eth-sri/lmql", "أطر العمل الأساسية", "federal-executive", "query-language"),
    ("Outlines", "https://github.com/outlines-dev/outlines", "أطر العمل الأساسية", "federal-executive", "structured-generation"),
    ("Marvin", "https://github.com/PrefectHQ/marvin", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("txtai", "https://github.com/neuml/txtai", "أطر العمل الأساسية", "federal-executive", "data-framework"),
    ("R2R", "https://github.com/SciPhi-AI/R2R", "أطر العمل الأساسية", "federal-executive", "rag"),
    ("SimpleAIChat", "https://github.com/minimaxir/simpleaichat", "أطر العمل الأساسية", "federal-executive", "chat"),
    ("YAML-agents", "https://github.com/kyrolabs/yaml-agents", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("AgentKit", "https://github.com/holistic-ai/agentkit", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("TaskWeaver", "https://github.com/microsoft/TaskWeaver", "أطر العمل الأساسية", "federal-executive", "code-framework"),
    ("WrenAI", "https://github.com/Canner/WrenAI", "أطر العمل الأساسية", "federal-executive", "data-framework"),
    ("Vanna", "https://github.com/vanna-ai/vanna", "أطر العمل الأساسية", "federal-executive", "data-framework"),
    ("Dataherald", "https://github.com/Dataherald/dataherald", "أطر العمل الأساسية", "federal-executive", "data-framework"),
    ("Chains (Cohere)", "https://github.com/cohere-ai/chains", "أطر العمل الأساسية", "federal-executive", "prompt-framework"),
    ("Smolagents", "https://github.com/huggingface/smolagents", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("PydanticAI", "https://github.com/pydantic/pydantic-ai", "أطر العمل الأساسية", "federal-executive", "orchestration"),
    ("Agno (Phidata)", "https://github.com/phidatahq/phidata", "أطر العمل الأساسية", "federal-executive", "orchestration"),

    # ===== وكلاء برمجيين وتطوير (Coding Agents) -> states-infrastructure =====
    ("Aider", "https://github.com/paul-gauthier/aider", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("Open Interpreter", "https://github.com/OpenInterpreter/open-interpreter", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("screenshot-to-code", "https://github.com/abi/screenshot-to-code", "وكلاء برمجيين وتطوير", "states-infrastructure", "ui-coding"),
    ("Automata", "https://github.com/emrgnt-cmplxty/automata", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("AutoPR", "https://github.com/irgolic/AutoPR", "وكلاء برمجيين وتطوير", "states-infrastructure", "pr-automation"),
    ("Devika", "https://github.com/stitionai/devika", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("Continue", "https://github.com/continuedev/continue", "وكلاء برمجيين وتطوير", "states-infrastructure", "ide-assistant"),
    ("OpenAgents", "https://github.com/xlang-ai/OpenAgents", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("Bloop", "https://github.com/BloopAI/bloop", "وكلاء برمجيين وتطوير", "states-infrastructure", "code-search"),
    ("BondAI", "https://github.com/knowsuchagency/bondai", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("Blinky", "https://github.com/maximz/blinky", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("bumpgen", "https://github.com/bumpgen/bumpgen", "وكلاء برمجيين وتطوير", "states-infrastructure", "dependency-upgrade"),
    ("BeeBot", "https://github.com/AI-BeeBot/beeBot", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("BambooAI", "https://github.com/rom1504/bambooai", "وكلاء برمجيين وتطوير", "states-infrastructure", "data-analysis"),
    ("GPT Pilot", "https://github.com/Pythagora-io/gpt-pilot", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("Goose (Block)", "https://github.com/block/goose", "وكلاء برمجيين وتطوير", "states-infrastructure", "ide-assistant"),
    ("Gemini CLI (Google)", "https://github.com/google-gemini/gemini-cli", "وكلاء برمجيين وتطوير", "states-infrastructure", "cli-coding"),
    ("GitHub Copilot CLI", "https://github.com/github/copilot-cli", "وكلاء برمجيين وتطوير", "states-infrastructure", "cli-coding"),
    ("bolt.diy", "https://github.com/bolt-foundry/bolt.diy", "وكلاء برمجيين وتطوير", "states-infrastructure", "ui-coding"),
    ("OpenCode", "https://github.com/opencode-ai/opencode", "وكلاء برمجيين وتطوير", "states-infrastructure", "cli-coding"),
    ("Refact", "https://github.com/smallcloudai/refact", "وكلاء برمجيين وتطوير", "states-infrastructure", "ide-assistant"),
    ("PR-Agent", "https://github.com/Codium-ai/pr-agent", "وكلاء برمجيين وتطوير", "states-infrastructure", "pr-review"),
    ("ToRA", "https://github.com/microsoft/ToRA", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("DevOpsGPT", "https://github.com/kuafuai/DevOpsGPT", "وكلاء برمجيين وتطوير", "states-infrastructure", "devops-automation"),
    ("AutoAgent", "https://github.com/AI-OpenAuto/AutoAgent", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("CodeGPT", "https://github.com/CodeGPT-org/CodeGPT", "وكلاء برمجيين وتطوير", "states-infrastructure", "ide-assistant"),
    ("Roo-Code", "https://github.com/RooVetGit/Roo-Code", "وكلاء برمجيين وتطوير", "states-infrastructure", "ide-assistant"),
    ("trae-agent (ByteDance)", "https://github.com/bytedance/trae-agent", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("kwaak", "https://github.com/kwaak-ai/kwaak", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("Mermaid", "https://github.com/mermaid-js/mermaid", "وكلاء برمجيين وتطوير", "states-infrastructure", "diagram-generation"),
    ("Pi", "https://github.com/pi-ai/pi", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("plandex", "https://github.com/plandex-ai/plandex", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("open-swe", "https://github.com/langchain-ai/open-swe", "وكلاء برمجيين وتطوير", "states-infrastructure", "swe-automation"),
    ("Grinta", "https://github.com/grinta-ai/grinta", "وكلاء برمجيين وتطوير", "states-infrastructure", "coding"),
    ("Claude Code (Anthropic)", "https://github.com/anthropics/claude-code", "وكلاء برمجيين وتطوير", "states-infrastructure", "cli-coding"),

    # ===== وكلاء تصفح وأتمتة (Browsing & Automation) -> states-infrastructure =====
    ("Browser-Use", "https://github.com/browser-use/browser-use", "وكلاء تصفح وأتمتة", "states-infrastructure", "browser-automation"),
    ("Skyvern", "https://github.com/Skyvern-AI/skyvern", "وكلاء تصفح وأتمتة", "states-infrastructure", "browser-automation"),
    ("RestGPT", "https://github.com/Yifan-Song793/RestGPT", "وكلاء تصفح وأتمتة", "states-infrastructure", "api-automation"),
    ("WebQA-Agent", "https://github.com/WebQA-Agent/WebQA-Agent", "وكلاء تصفح وأتمتة", "states-infrastructure", "web-qa"),
    ("ADAS", "https://github.com/ADAS-AI/ADAS", "وكلاء تصفح وأتمتة", "states-infrastructure", "automation"),
    ("LiteWebAgent", "https://github.com/LiteWebAgent/LiteWebAgent", "وكلاء تصفح وأتمتة", "states-infrastructure", "browser-automation"),
    ("AgenticSeek", "https://github.com/agenticseek/agenticseek", "وكلاء تصفح وأتمتة", "states-infrastructure", "search-automation"),
    ("OpenWorker", "https://github.com/andrewyng/openworker", "وكلاء تصفح وأتمتة", "states-infrastructure", "automation"),
    ("UI-TARS-desktop", "https://github.com/bytedance/UI-TARS-desktop", "وكلاء تصفح وأتمتة", "states-infrastructure", "gui-automation"),
    ("UFO (Microsoft)", "https://github.com/microsoft/UFO", "وكلاء تصفح وأتمتة", "states-infrastructure", "gui-automation"),
    ("ClaudeClaw", "https://github.com/sbusso/claudeclaw", "وكلاء تصفح وأتمتة", "states-infrastructure", "automation"),
    ("clawdbot", "https://github.com/clawd-meme/clawdbot", "وكلاء تصفح وأتمتة", "states-infrastructure", "automation"),
    ("RustClaw", "https://github.com/RustClawBot/rustclaw", "وكلاء تصفح وأتمتة", "states-infrastructure", "automation"),
    ("Cal.ai", "https://github.com/calcom/cal.ai", "وكلاء تصفح وأتمتة", "states-infrastructure", "scheduling-automation"),
    ("n8n", "https://github.com/n8n-io/n8n", "وكلاء تصفح وأتمتة", "states-infrastructure", "workflow-automation"),
    ("Activepieces", "https://github.com/activepieces/activepieces", "وكلاء تصفح وأتمتة", "states-infrastructure", "workflow-automation"),
    ("Huginn", "https://github.com/huginn/huginn", "وكلاء تصفح وأتمتة", "states-infrastructure", "automation"),
    ("StackStorm", "https://github.com/StackStorm/stax", "وكلاء تصفح وأتمتة", "states-infrastructure", "automation"),

    # ===== وكلاء بحث وأكاديميين (Research Agents) -> states-science =====
    ("GPT Researcher", "https://github.com/assafelovic/gpt-researcher", "وكلاء بحث وأكاديميين", "states-science", "research"),
    ("STORM (Stanford)", "https://github.com/stanford-oval/storm", "وكلاء بحث وأكاديميين", "states-science", "research"),
    ("AI Scientist", "https://github.com/SakanaAI/AI-Scientist", "وكلاء بحث وأكاديميين", "states-science", "research"),
    ("DeepAnalyze", "https://github.com/DeepAnalyze/DeepAnalyze", "وكلاء بحث وأكاديميين", "states-science", "research"),
    ("Co-Sight 2.0", "https://github.com/ZTE/Co-Sight", "وكلاء بحث وأكاديميين", "states-science", "research"),
    ("Deep Research", "https://github.com/scienceaix/deepresearch", "وكلاء بحث وأكاديميين", "states-science", "deep-research"),

    # ===== الذاكرة والبيانات (Memory & Data) -> memory =====
    ("MemGPT (Letta)", "https://github.com/letta-ai/letta", "الذاكرة والبيانات", "memory", "memory"),
    ("Mem0", "https://github.com/mem0ai/mem0", "الذاكرة والبيانات", "memory", "memory"),
    ("Zep", "https://github.com/getzep/zep", "الذاكرة والبيانات", "memory", "memory"),
    ("Marqo", "https://github.com/marqo-ai/marqo", "الذاكرة والبيانات", "memory", "vector-search"),
    ("Vald", "https://github.com/vdaas/vald", "الذاكرة والبيانات", "memory", "vector-search"),
    ("Vectra", "https://github.com/StevenWeathers/vectra", "الذاكرة والبيانات", "memory", "vector-search"),
    ("Qdrant", "https://github.com/qdrant/qdrant", "الذاكرة والبيانات", "memory", "vector-db"),
    ("Weaviate", "https://github.com/weaviate/weaviate", "الذاكرة والبيانات", "memory", "vector-db"),
    ("Chroma", "https://github.com/chroma-core/chroma", "الذاكرة والبيانات", "memory", "vector-db"),
    ("Milvus", "https://github.com/milvus-io/milvus", "الذاكرة والبيانات", "memory", "vector-db"),
    ("pgvector", "https://github.com/pgvector/pgvector", "الذاكرة والبيانات", "memory", "vector-db"),
    ("FAISS", "https://github.com/facebookresearch/faiss", "الذاكرة والبيانات", "memory", "vector-search"),
    ("Cognee", "https://github.com/topoteretes/cognee", "الذاكرة والبيانات", "memory", "memory"),

    # ===== وكلاء إبداعيين ومحاكاة (Creative & Simulation) -> states-culture =====
    ("AI-town", "https://github.com/a16z-infra/ai-town", "وكلاء إبداعيين ومحاكاة", "states-culture", "simulation"),
    ("Yoyo", "https://github.com/yoyo-agent/yoyo", "وكلاء إبداعيين ومحاكاة", "states-culture", "creative"),
    ("OpenAgents Network", "https://github.com/openagents-network/openagents-network", "وكلاء إبداعيين ومحاكاة", "states-culture", "simulation"),
    ("ChatDev", "https://github.com/OpenBMB/ChatDev", "وكلاء إبداعيين ومحاكاة", "states-culture", "simulation"),
    ("CAMEL", "https://github.com/camel-ai/camel", "وكلاء إبداعيين ومحاكاة", "states-culture", "multi-agent"),
    ("AgentVerse (creative)", "https://github.com/OpenBMB/AgentVerse", "وكلاء إبداعيين ومحاكاة", "states-culture", "simulation"),
    ("ShortGPT", "https://github.com/RayVentura/ShortGPT", "وكلاء إبداعيين ومحاكاة", "states-culture", "video-generation"),
    ("VirtualHome", "https://github.com/xavierpuigf/virtualhome", "وكلاء إبداعيين ومحاكاة", "states-culture", "simulation"),
    ("Habitat (Meta)", "https://github.com/facebookresearch/habitat-sim", "وكلاء إبداعيين ومحاكاة", "states-culture", "simulation"),
    ("Overcooked-AI", "https://github.com/HumanCompatibleAI/overcooked_ai", "وكلاء إبداعيين ومحاكاة", "states-culture", "simulation"),
    ("Neural MMO", "https://github.com/neuralmmo/neuralmmo", "وكلاء إبداعيين ومحاكاة", "states-culture", "simulation"),
    ("MineDojo", "https://github.com/MineDojo/MineDojo", "وكلاء إبداعيين ومحاكاة", "states-culture", "simulation"),
    ("Voyager", "https://github.com/MineDojo/Voyager", "وكلاء إبداعيين ومحاكاة", "states-culture", "simulation"),
    ("CraftAssist (Facebook)", "https://github.com/facebookresearch/craftassist", "وكلاء إبداعيين ومحاكاة", "states-culture", "simulation"),
    ("TextWorld (Microsoft)", "https://github.com/microsoft/TextWorld", "وكلاء إبداعيين ومحاكاة", "states-culture", "simulation"),

    # ===== وكلاء ألعاب (Gaming Agents) -> states-culture =====
    ("Overcooked-AI (game)", "https://github.com/HumanCompatibleAI/overcooked_ai", "وكلاء ألعاب", "states-culture", "gaming"),
    ("Neural MMO (game)", "https://github.com/neuralmmo/neuralmmo", "وكلاء ألعاب", "states-culture", "gaming"),
    ("MineDojo (game)", "https://github.com/MineDojo/MineDojo", "وكلاء ألعاب", "states-culture", "gaming"),
    ("Voyager (game)", "https://github.com/MineDojo/Voyager", "وكلاء ألعاب", "states-culture", "gaming"),

    # ===== وكلاء محادثة ومساعدين (Conversational Agents) -> states-culture =====
    ("AgentGPT", "https://github.com/reworkd/AgentGPT", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("AIlice", "https://github.com/myshell-ai/AIlice", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("Autonomous HR Chatbot", "https://github.com/stepanogil/autonomous-hr-chatbot", "وكلاء محادثة ومساعدين", "states-culture", "hr-assistant"),
    ("BabyAGI", "https://github.com/yoheinakajima/babyagi", "وكلاء محادثة ومساعدين", "federal-executive", "task-management"),
    ("BabyBeeAGI", "https://yoheinakajima.com/babybeeagi-task-management-and-functionality-expansion-on-top-of-babyagi/", "وكلاء محادثة ومساعدين", "federal-executive", "task-management"),
    ("BabyCatAGI", "https://replit.com/@YoheiNakajima/BabyCatAGI", "وكلاء محادثة ومساعدين", "federal-executive", "task-management"),
    ("BabyDeerAGI", "https://twitter.com/yoheinakajima/status/1666313838868992001", "وكلاء محادثة ومساعدين", "federal-executive", "task-management"),
    ("BabyElfAGI", "https://twitter.com/yoheinakajima/status/1678443482866933760", "وكلاء محادثة ومساعدين", "federal-executive", "task-management"),
    ("Peak-AI-agent-stack", "https://github.com/dleerdefi/peak-ai-agent-stack", "وكلاء محادثة ومساعدين", "federal-executive", "agent-stack"),
    ("Lobe Chat", "https://github.com/lobehub/lobe-chat", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("Khoj", "https://github.com/khoj-ai/khoj", "وكلاء محادثة ومساعدين", "states-culture", "personal-assistant"),
    ("Jan.ai", "https://github.com/janhq/jan", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("Nanobot", "https://github.com/nanobot-ai/nanobot", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("OpenClaw (conv)", "https://github.com/openclaw/openclaw", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("Hermes Agent (conv)", "https://github.com/nousresearch/hermes-agent", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("ClaudeClaw (conv)", "https://github.com/sbusso/claudeclaw", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("clawdbot (conv)", "https://github.com/clawd-meme/clawdbot", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("RustClaw (conv)", "https://github.com/RustClawBot/rustclaw", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("NullClaw", "https://github.com/nullclaw/nullclaw", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("PicoClaw", "https://github.com/picoclaw/picoclaw", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("MimiClaw", "https://github.com/mimiclaw/mimiclaw", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("SupaClaw", "https://github.com/supaclaw/supaclaw", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("TinyClaw", "https://github.com/tinyclaw/tinyclaw", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("TrinityClaw", "https://github.com/trinityclaw/trinityclaw", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("AstrBot", "https://github.com/AstrBot/AstrBot", "وكلاء محادثة ومساعدين", "states-culture", "conversational"),
    ("Multi-Agent Orchestrator", "https://github.com/ParthivPandya/multi-agent-orchestrator", "وكلاء محادثة ومساعدين", "federal-executive", "orchestration"),

    # ===== أمان وحوكمة (Security & Governance) -> security =====
    ("Agent Governance Toolkit (Microsoft)", "https://github.com/microsoft/agent-governance-toolkit", "أمان وحوكمة", "governance", "governance"),
    ("IronCurtain", "https://github.com/ironcurtain/ironcurtain", "أمان وحوكمة", "security", "security"),
    ("Agentic Security", "https://github.com/agentic-security/agentic-security", "أمان وحوكمة", "security", "security-testing"),
    ("mcp-scan", "https://github.com/mcp-scan/mcp-scan", "أمان وحوكمة", "security", "security-scanning"),
    ("Deepfence-ThreatMapper", "https://github.com/deepfence/ThreatMapper", "أمان وحوكمة", "security", "threat-mapping"),
    ("Falco", "https://github.com/falcosecurity/falco", "أمان وحوكمة", "security", "runtime-security"),
    ("Cilium", "https://github.com/cilium/cilium", "أمان وحوكمة", "security", "network-security"),
    ("Sandbox Runtime (Anthropic)", "https://github.com/anthropics/sandbox-runtime", "أمان وحوكمة", "security", "sandbox-runtime"),

    # ===== أدوات تقييم واختبار (Evaluation & Testing) -> governance-audits =====
    ("AgentBench (Tsinghua)", "https://github.com/THUDM/AgentBench", "أدوات تقييم واختبار", "governance-audits", "evaluation"),
    ("AgentBoard", "https://github.com/AgentBoard/AgentBoard", "أدوات تقييم واختبار", "governance-audits", "evaluation"),
    ("SWE-bench", "https://github.com/princeton-nlp/SWE-bench", "أدوات تقييم واختبار", "governance-audits", "evaluation"),
    ("LangSmith", "https://github.com/langchain-ai/langsmith", "أدوات تقييم واختبار", "governance-audits", "observability"),
    ("DeepEval", "https://github.com/confident-ai/deepeval", "أدوات تقييم واختبار", "governance-audits", "evaluation"),
    ("LangTest", "https://github.com/JohnSnowLabs/langtest", "أدوات تقييم واختبار", "governance-audits", "evaluation"),
    ("SEAL", "https://github.com/SEAL-Evaluation/SEAL", "أدوات تقييم واختبار", "governance-audits", "evaluation"),
    ("AgentEval", "https://github.com/AgentEval/AgentEval", "أدوات تقييم واختبار", "governance-audits", "evaluation"),
    ("ToolTalk", "https://github.com/ToolTalk/ToolTalk", "أدوات تقييم واختبار", "governance-audits", "tool-evaluation"),
    ("VisualWebArena", "https://github.com/VisualWebArena/VisualWebArena", "أدوات تقييم واختبار", "governance-audits", "web-evaluation"),
    ("Mind2Web", "https://github.com/OSU-NLP-Group/Mind2Web", "أدوات تقييم واختبار", "governance-audits", "web-evaluation"),
    ("WebLINX", "https://github.com/McGill-NLP/WebLINX", "أدوات تقييم واختبار", "governance-audits", "web-evaluation"),
    ("CRUD-RAG", "https://github.com/CRUD-RAG/CRUD-RAG", "أدوات تقييم واختبار", "governance-audits", "rag-evaluation"),
    ("bananalyzer", "https://github.com/reworkd/bananalyzer", "أدوات تقييم واختبار", "governance-audits", "evaluation"),
    ("ClawBench", "https://github.com/clawbench/clawbench", "أدوات تقييم واختبار", "governance-audits", "evaluation"),
    ("GAIA", "https://github.com/GAIA-Benchmark/GAIA", "أدوات تقييم واختبار", "governance-audits", "evaluation"),
    ("RuLES", "https://github.com/RuLES/RuLES", "أدوات تقييم واختبار", "governance-audits", "evaluation"),
    ("ToolBench", "https://github.com/sambanova/toolbench", "أدوات تقييم واختبار", "governance-audits", "tool-evaluation"),
    ("ToolEmu", "https://github.com/ryokamoi/toolemu", "أدوات تقييم واختبار", "governance-audits", "tool-evaluation"),

    # ===== وكلاء مؤسسيين (Enterprise Agents) -> federal-executive =====
    ("Microsoft Agent Framework (enterprise)", "https://github.com/microsoft/agent-framework", "وكلاء مؤسسيين", "federal-executive", "enterprise"),
    ("Dify Enterprise", "https://github.com/langgenius/dify", "وكلاء مؤسسيين", "federal-executive", "enterprise"),
    ("IBM watsonx", "https://github.com/IBM/watsonx-ai", "وكلاء مؤسسيين", "federal-executive", "enterprise"),
    ("Robusta", "https://github.com/robusta-dev/robusta", "وكلاء مؤسسيين", "states-infrastructure", "devops"),
    ("Keep", "https://github.com/keephq/keep", "وكلاء مؤسسيين", "observability", "alerting"),
    ("Cloud-Custodian", "https://github.com/cloud-custodian/cloud-custodian", "وكلاء مؤسسيين", "states-infrastructure", "cloud-governance"),
    ("DevOps-Monkey", "https://github.com/devops-monkey/devops-monkey", "وكلاء مؤسسيين", "states-infrastructure", "devops"),
    ("Log-Whisperer", "https://github.com/log-whisperer/log-whisperer", "وكلاء مؤسسيين", "observability", "log-analysis"),
    ("K8sGPT", "https://github.com/k8sgpt-ai/k8sgpt", "وكلاء مؤسسيين", "states-infrastructure", "kubernetes"),
    ("Bytebase", "https://github.com/bytebase/bytebase", "وكلاء مؤسسيين", "states-infrastructure", "database-management"),

    # ===== خوادم MCP وتكاملات (MCP Servers) -> tools =====
    ("GitHub MCP", "https://github.com/github/github-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("Playwright MCP", "https://github.com/microsoft/playwright-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("Filesystem MCP", "https://github.com/modelcontextprotocol/filesystem-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("Brave Search MCP", "https://github.com/modelcontextprotocol/brave-search-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("Slack MCP", "https://github.com/modelcontextprotocol/slack-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("Notion MCP", "https://github.com/modelcontextprotocol/notion-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("PostgreSQL MCP", "https://github.com/modelcontextprotocol/postgresql-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("Google Maps MCP", "https://github.com/modelcontextprotocol/google-maps-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("Taskade MCP", "https://github.com/taskade/taskade-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("MCP-Fetch", "https://github.com/modelcontextprotocol/fetch-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("MCP-Memory", "https://github.com/modelcontextprotocol/memory-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("MCP-SQLite", "https://github.com/modelcontextprotocol/sqlite-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("MCP-Git", "https://github.com/modelcontextprotocol/git-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("MCP-Puppeteer", "https://github.com/modelcontextprotocol/puppeteer-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("MCP-Search", "https://github.com/modelcontextprotocol/search-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("MCP-Docker", "https://github.com/modelcontextprotocol/docker-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("MCP-Spotify", "https://github.com/modelcontextprotocol/spotify-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),
    ("MCP-GSheets", "https://github.com/modelcontextprotocol/gsheets-mcp", "خوادم MCP وتكاملات", "tools", "mcp-server"),

    # ===== وكلاء أتمتة الأجهزة المحمولة (Mobile Automation) -> states-infrastructure =====
    ("AppAgent (Tencent)", "https://github.com/AppAgent/AppAgent", "وكلاء أتمتة الأجهزة المحمولة", "states-infrastructure", "mobile-automation"),
    ("Mobile-Agent", "https://github.com/Mobile-Agent/Mobile-Agent", "وكلاء أتمتة الأجهزة المحمولة", "states-infrastructure", "mobile-automation"),
    ("DroidBot", "https://github.com/honeynet/droidbot", "وكلاء أتمتة الأجهزة المحمولة", "states-infrastructure", "mobile-automation"),

    # ===== وكلاء متخصصون (Specialized) -> split by domain =====
    ("BioChatter", "https://github.com/biocypher/BioChatter", "وكلاء متخصصون (صحة)", "states-health", "biomedical"),
    ("MedAgents", "https://github.com/MedAgents/MedAgents", "وكلاء متخصصون (صحة)", "states-health", "medical"),
    ("Clinical-Trial-Agent", "https://github.com/clinical-trial-agent/clinical-trial-agent", "وكلاء متخصصون (صحة)", "states-health", "clinical-trials"),
    ("LawGPT-Agent", "https://github.com/LawGPT-Agent/LawGPT-Agent", "وكلاء متخصصون (قانون)", "states-law", "legal"),
    ("LegalBERT-Agent", "https://github.com/legalbert/legalbert-agent", "وكلاء متخصصون (قانون)", "states-law", "legal"),
    ("FinGPT-Agent", "https://github.com/FinGPT/FinGPT-Agent", "وكلاء متخصصون (تمويل)", "states-finance", "financial"),
    ("Trading-Gym", "https://github.com/trading-gym/trading-gym", "وكلاء متخصصون (تمويل)", "states-finance", "trading"),
    ("QuantAgent", "https://github.com/QuantAgent/QuantAgent", "وكلاء متخصصون (تمويل)", "states-finance", "quantitative"),
    ("RiskAgent", "https://github.com/RiskAgent/RiskAgent", "وكلاء متخصصون (تمويل)", "states-finance", "risk"),
    ("ChemCrow", "https://github.com/chemcrow/chemcrow", "وكلاء متخصصون (كيمياء)", "states-science", "chemistry"),
    ("Bio-SPICE", "https://github.com/biospice/biospice", "وكلاء متخصصون (كيمياء)", "states-science", "biochemistry"),
    ("Protein-Agent", "https://github.com/protein-agent/protein-agent", "وكلاء متخصصون (كيمياء)", "states-science", "protein"),

    # ===== وكلاء متعددو الوسائط (Multimodal Agents) -> states-culture =====
    ("Audiobox (Meta)", "https://github.com/facebookresearch/audiobox", "وكلاء متعددو الوسائط", "states-culture", "audio"),
    ("MusicGen-Agent", "https://github.com/musicgen-agent/musicgen-agent", "وكلاء متعددو الوسائط", "states-culture", "music-generation"),
    ("Video-LLaVA-Agent", "https://github.com/video-llava/video-llava-agent", "وكلاء متعددو الوسائط", "states-culture", "video-understanding"),
    ("ImageBind-Agent", "https://github.com/imagebind-agent/imagebind-agent", "وكلاء متعددو الوسائط", "states-culture", "multimodal-binding"),
    ("SeamlessM4T-Agent", "https://github.com/seamless-m4t/seamless-m4t-agent", "وكلاء متعددو الوسائط", "states-culture", "translation"),
    ("CLIP-Agent", "https://github.com/clip-agent/clip-agent", "وكلاء متعددو الوسائط", "states-culture", "vision-language"),
    ("Stable-Diffusion-Agent", "https://github.com/stable-diffusion-agent/stable-diffusion-agent", "وكلاء متعددو الوسائط", "states-culture", "image-generation"),
    ("AnimateDiff-Agent", "https://github.com/AnimateDiff/AnimateDiff-Agent", "وكلاء متعددو الوسائط", "states-culture", "animation"),
    ("GPT-4o-TTS-Agent", "https://github.com/gpt-4o-tts/gpt-4o-tts-agent", "وكلاء متعددو الوسائط", "states-culture", "tts"),

    # ===== وكلاء صوت (Voice Agents) -> states-culture =====
    ("Pipecat", "https://github.com/pipecat-ai/pipecat", "وكلاء صوت", "states-culture", "voice"),
    ("LiveKit Agents", "https://github.com/livekit/agents", "وكلاء صوت", "states-culture", "voice"),
    ("Sayna", "https://github.com/sayna-ai/sayna", "وكلاء صوت", "states-culture", "voice"),
    ("Rasa", "https://github.com/RasaHQ/rasa", "وكلاء صوت", "states-culture", "conversational-ai"),

    # ===== وكلاء تحليل بيانات (Data Analysis) -> states-science =====
    ("BambooAI (analysis)", "https://github.com/rom1504/bambooai", "وكلاء تحليل بيانات", "states-science", "data-analysis"),
    ("PandasAI", "https://github.com/Sinaptik-ai/pandas-ai", "وكلاء تحليل بيانات", "states-science", "data-analysis"),
    ("Plotly-Dash-Agent", "https://github.com/plotly-dash-agent/plotly-dash-agent", "وكلاء تحليل بيانات", "states-science", "data-visualization"),
    ("ThoughtSpot-Agent", "https://github.com/thoughtspot/thoughtspot-agent", "وكلاء تحليل بيانات", "states-science", "data-analytics"),

    # ===== وكلاء DevOps والسحابة (DevOps & Cloud) -> states-infrastructure =====
    ("K8sGPT (devops)", "https://github.com/k8sgpt-ai/k8sgpt", "وكلاء DevOps والسحابة", "states-infrastructure", "kubernetes"),
    ("Robusta (devops)", "https://github.com/robusta-dev/robusta", "وكلاء DevOps والسحابة", "states-infrastructure", "devops"),
    ("Keep (devops)", "https://github.com/keephq/keep", "وكلاء DevOps والسحابة", "observability", "alerting"),
    ("Cloud-Custodian (devops)", "https://github.com/cloud-custodian/cloud-custodian", "وكلاء DevOps والسحابة", "states-infrastructure", "cloud-governance"),
    ("DevOps-Monkey (devops)", "https://github.com/devops-monkey/devops-monkey", "وكلاء DevOps والسحابة", "states-infrastructure", "devops"),
    ("Log-Whisperer (devops)", "https://github.com/log-whisperer/log-whisperer", "وكلاء DevOps والسحابة", "observability", "log-analysis"),
    ("OpenSRE", "https://github.com/opensre/opensre", "وكلاء DevOps والسحابة", "states-infrastructure", "sre"),

    # ===== أدوات وبنى تحتية أخرى (Other Tools) -> tools =====
    ("Ollama", "https://github.com/ollama/ollama", "أدوات وبنى تحتية أخرى", "models", "local-models"),
    ("PrivateGPT", "https://github.com/zylon-ai/private-gpt", "أدوات وبنى تحتية أخرى", "tools", "rag"),
    ("LM Studio", "https://github.com/lmstudio-ai/lmstudio", "أدوات وبنى تحتية أخرى", "models", "local-models"),
    ("Firecrawl", "https://github.com/mendableai/firecrawl", "أدوات وبنى تحتية أخرى", "tools", "web-scraping"),
    ("Crawl4AI", "https://github.com/unclecode/crawl4ai", "أدوات وبنى تحتية أخرى", "tools", "web-scraping"),
    ("Octomind", "https://github.com/octomind/octomind", "أدوات وبنى تحتية أخرى", "tools", "testing"),
    ("Zo Computer", "https://github.com/zo-computer/zo-computer", "أدوات وبنى تحتية أخرى", "tools", "computer-use"),
    ("MaxKB", "https://github.com/1Panel-dev/MaxKB", "أدوات وبنى تحتية أخرى", "tools", "knowledge-base"),
    ("PaperOrchestra", "https://github.com/paperorchestra/paperorchestra", "أدوات وبنى تحتية أخرى", "tools", "research"),
    ("teamcopilot", "https://github.com/teamcopilot/teamcopilot", "أدوات وبنى تحتية أخرى", "tools", "team-assistant"),
    ("Waku", "https://github.com/waku-ai/waku", "أدوات وبنى تحتية أخرى", "tools", "agent-tool"),
    ("Claude Desktop Intelligence", "https://github.com/claude-desktop-intelligence/claude-desktop-intelligence", "أدوات وبنى تحتية أخرى", "tools", "desktop-intelligence"),
    ("ZeroClaw", "https://github.com/zeroclaw/zeroclaw", "أدوات وبنى تحتية أخرى", "tools", "agent-tool"),
    ("NanoClaw", "https://github.com/nanoclaw/nanoclaw", "أدوات وبنى تحتية أخرى", "tools", "agent-tool"),
    ("NemoClaw (NVIDIA)", "https://github.com/nvidia/nemoclaw", "أدوات وبنى تحتية أخرى", "tools", "agent-tool"),
    ("clawagents", "https://github.com/clawagents/clawagents", "أدوات وبنى تحتية أخرى", "tools", "agent-tool"),
    ("OmniRoute", "https://github.com/omniroute/omniroute", "أدوات وبنى تحتية أخرى", "tools", "routing"),
    ("GenericAgent", "https://github.com/lsdefine/GenericAgent", "أدوات وبنى تحتية أخرى", "tools", "agent-tool"),
    ("Omnigent", "https://github.com/omnigent/omnigent", "أدوات وبنى تحتية أخرى", "tools", "agent-tool"),

    # ===== وكلاء أتمتة سير العمل (Workflow Automation) -> states-infrastructure =====
    ("n8n (workflow)", "https://github.com/n8n-io/n8n", "وكلاء أتمتة سير العمل", "states-infrastructure", "workflow-automation"),
    ("Activepieces (workflow)", "https://github.com/activepieces/activepieces", "وكلاء أتمتة سير العمل", "states-infrastructure", "workflow-automation"),
    ("Huginn (workflow)", "https://github.com/huginn/huginn", "وكلاء أتمتة سير العمل", "states-infrastructure", "workflow-automation"),
    ("StackStorm (workflow)", "https://github.com/StackStorm/stax", "وكلاء أتمتة سير العمل", "states-infrastructure", "workflow-automation"),
    ("Windmill", "https://github.com/windmill-labs/windmill", "وكلاء أتمتة سير العمل", "states-infrastructure", "workflow-automation"),
    ("Bytebase (workflow)", "https://github.com/bytebase/bytebase", "وكلاء أتمتة سير العمل", "states-infrastructure", "database-management"),
]

# المكان المخصص -> المسار داخل المستودع
DOMAIN_PATH = {
    "federal-executive": "federal/executive",
    "states-infrastructure": "states/infrastructure",
    "states-science": "states/science",
    "states-culture": "states/culture",
    "states-finance": "states/finance",
    "states-health": "states/health",
    "states-law": "states/law",
    "memory": "memory",
    "tools": "tools",
    "governance": "governance",
    "governance-audits": "governance/audits",
    "security": "security",
    "observability": "observability",
    "models": "models",
}
