-- ============================================================
-- AMOS-Federation Migration 003 — audit_log.seq
-- الهدف: ترتيب رتيب موثوق لسلسلة البصمات في PostgreSQL
-- النطاق: federal/executive/services
-- المالك: federal/executive/services
-- تاريخ الإنشاء: 2026-08-16
-- ============================================================
--
-- السبب الجذري:
-- 001_init.sql عرّف audit_log.id كـ UUID PRIMARY KEY DEFAULT gen_random_uuid().
-- الكود كان يقرأ آخر بصمة عبر «ORDER BY id DESC LIMIT 1»، وترتيب UUID عشوائي
-- في PostgreSQL، فكانت سلسلة الكتل تُبنى على سجل غير مُعرَّف — أي كسر صامت
-- للسلسلة عند التشغيل على PostgreSQL. هذه الهجرة تضيف عمودًا متزايدًا رتيبًا
-- (seq) وهو الأساس الوحيد المعتمد للترتيب في events.py.
--
-- SQLite لا يحتاج هذه الهجرة: الجدول يُنشأ هناك عبر
-- amos_federation.common.database.ensure_audit_log_table() الذي يعرّف
-- seq INTEGER PRIMARY KEY AUTOINCREMENT مباشرة.

ALTER TABLE audit_log
    ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- ترتيب الصفوف القائمة قبل الهجرة يعتمد على timestamp، وهو أفضل تقريب متاح
-- للصفوف التاريخية. الصفوف الجديدة تحصل على seq تصاعدي مضمون.
CREATE UNIQUE INDEX IF NOT EXISTS idx_audit_seq ON audit_log (seq);
